export const itensFornecimento = {
  trigo: { nome: "Trigo (1 kg)", custo: 2, peso: "-" },
  farinha: { nome: "Farinha (1 kg)", custo: 4, peso: "-" },
  galinha: { nome: "Galinha", custo: 4, peso: "0,25 kg" },
  ferro: { nome: "Ferro (1 kg)", custo: 20, peso: "1 kg" },
  tabaco: { nome: "Tabaco (1 kg)", custo: 100, peso: "1 kg" },
  cobre: { nome: "Cobre (1 kg)", custo: 100, peso: "1 kg" },
  canela: { nome: "Canela (0,5 kg)", custo: 100, peso: "0,5 kg" },
  bode: { nome: "Bode", custo: 100, peso: "-" },
  gengibre: { nome: "Gengibre (0,5 kg)", custo: 200, peso: "0,5 kg" },
  pimenta: { nome: "Pimenta (0,5 kg)", custo: 200, peso: "0,5 kg" },
  ovelha: { nome: "Ovelha", custo: 200, peso: "-" },
  porco: { nome: "Porco", custo: 300, peso: "-" },
  linho: { nome: "Linho (1 m²)", custo: 400, peso: "0,1 kg" },
  sal: { nome: "Sal (0,5 kg)", custo: 500, peso: "0,5 kg" },
  prata: { nome: "Prata (0,5 kg)", custo: 500, peso: "0,5 kg" },
  seda: { nome: "Seda (1 m²)", custo: 1000, peso: "0,1 kg" },
  vaca: { nome: "Vaca", custo: 1000, peso: "-" },
  acafrao: { nome: "Açafrão (0,5 kg)", custo: 1500, peso: "0,5 kg" },
  alho: { nome: "Alho (0,5 kg)", custo: 1500, peso: "0,5 kg" },
  boi: { nome: "Boi", custo: 1500, peso: "-" },
  ouro: { nome: "Ouro (0,5 kg)", custo: 5000, peso: "0,5 kg" },
  platina: { nome: "Platina (0,5 kg)", custo: 50000, peso: "0,5 kg" }
};