export const itensGerais = {
  // agulha_costura: { nome: "Agulha de costura", custo: 10, peso: "-" },
  // algemas_op: { nome: "Algemas (obra-prima)", custo: 5000, peso: "1 kg" },
  // algemas: { nome: "Algemas", custo: 1500, peso: "1 kg" },
  // algibeira: { nome: "Algibeira", custo: 100, peso: "0,25 kg" },
  // anzol: { nome: "Anzol", custo: 10, peso: "-" },
  // apito: { nome: "Apito de advertência", custo: 80, peso: "-" },
  // ariete: { nome: "Aríete", custo: 1000, peso: "10 kg" },
  // balde: { nome: "Balde (vazio)", custo: 10, peso: "1 kg" },
  // barr: { nome: "Barril (vazio)", custo: 200, peso: "15 kg" },
  // bau: { nome: "Baú (vazio)", custo: 200, peso: "12,5 kg" },
  // caneco: { nome: "Caneco de cerâmica", custo: 2, peso: "0,5 kg" },
  // caneta: { nome: "Caneta tinteiro", custo: 10, peso: "-" },
  cantil: { nome: "Cantil", custo: 100, peso: "2 kg" }
  // ,
  // cesto: { nome: "Cesto (vazio)", custo: 40, peso: "0,5 kg" },
  // cobertor: { nome: "Cobertor de inverno", custo: 50, peso: "1,5 kg" },
  // corda_canha: { nome: "Reda de Cânhamo (15 m)", custo: 100, peso: "5 kg" },
  // corda_seda: { nome: "Reda de seda (15 m)", custo: 1000, peso: "2,5 kg" },
  // corrente: { nome: "Corrente (3 m)", custo: 3000, peso: "1 kg" },
  // escada: { nome: "Escada (3 m)", custo: 5, peso: "10 kg" },
  // esmeril: { nome: "Esmeril", custo: 2, peso: "0,5 kg" },
  // espelho: { nome: "Espelho de metal pequeno", custo: 1000, peso: "0,25 kg" },
  // estrepes: { nome: "Estrepes", custo: 100, peso: "1 kg" },
  // fechadura_simples: { nome: "Fechadura muito simples", custo: 2000, peso: "0,5 kg" },
  // fechadura_padrao: { nome: "Fechadura padrão", custo: 4000, peso: "0,5 kg" },
  // fechadura_boa: { nome: "Fechadura boa", custo: 8000, peso: "0,5 kg" },
  // fechadura_incrivel: { nome: "Fechadura incrível", custo: 15000, peso: "0,5 kg" },
  // frasco: { nome: "Frasco (vazio)", custo: 3, peso: "0,75 kg" },
  // garrafa_vinho: { nome: "Garrafa de vinho (vidro)", custo: 200, peso: "-" },
  // giz: { nome: "Giz (1 pedaço)", custo: 1, peso: "-" },
  // jarro: { nome: "Jarro de cerâmica", custo: 3, peso: "4,5 kg" },
  // lanterna_coberta: { nome: "Lanterna coberta", custo: 700, peso: "1 kg" },
  // lanterna_furtafogo: { nome: "Lanterna furta-fogo", custo: 1200, peso: "1,5 kg" },
  // lenha: { nome: "Lenha (por dia)", custo: 1, peso: "10 kg" },
  // lona: { nome: "Lona (m²)", custo: 10, peso: "0,1 kg" },
  // luneta: { nome: "Luneta", custo: 100000, peso: "0,5 kg" },
  // marreta: { nome: "Marreta", custo: 100, peso: "5 kg" },
  // martelo: { nome: "Martelo", custo: 50, peso: "1 kg" },
  // mochila: { nome: "Mochila (vazia)", custo: 200, peso: "1 kg" },
  // oleo: { nome: "Óleo (500 ml)", custo: 10, peso: "0,5 kg" },
  // pa: { nome: "Pá", custo: 200, peso: "4 kg" },
  // panela: { nome: "Panela de ferro", custo: 50, peso: "5 kg" },
  // parafina: { nome: "Parafina", custo: 100, peso: "0,5 kg" },
  // pe_cabeca: { nome: "Pé de cabra", custo: 200, peso: "2,5 kg" },
  // pederneira: { nome: "Pederneira", custo: 100, peso: "-" },
  // isqueiro: { nome: "Isqueiro", custo: 100, peso: "-" },
  // pergaminho: { nome: "Pergaminho (folha)", custo: 20, peso: "-" },
  // picareta: { nome: "Picareta de mina", custo: 300, peso: "5 kg" },
  // pyton: { nome: "Píton", custo: 10, peso: "0,25 kg" },
  // porta_mapas: { nome: "Porta-mapas", custo: 100, peso: "0,25 kg" },
  // pote: { nome: "Pote de cerâmica", custo: 2, peso: "2,5 kg" },
  // racao: { nome: "Rações de viagem (por dia)", custo: 50, peso: "0,5 kg" },
  // rede_pesca: { nome: "Rede de pesca (5 x 5 m)", custo: 400, peso: "2,5 kg" },
  // Sabao: { nome: "Sabão (por kg)", custo: 50, peso: "0,5 kg" },
  // aco: { nome: "Saco (vazio)", custo: 10, peso: "0,25 kg" },
  // aco_dormir: { nome: "Saco de dormir", custo: 10, peso: "2,5 kg" },
  // sino: { nome: "Sino", custo: 100, peso: "-" },
  // sinete: { nome: "Sinete", custo: 500, peso: "-" },
  // talha: { nome: "Talha ou sisal", custo: 500, peso: "2,5 kg" },
  // tenda: { nome: "Tenda", custo: 1000, peso: "10 kg" },
  // tinta: { nome: "Tinta (vidro de 30 ml)", custo: 800, peso: "-" },
  // tocha: { nome: "Tocha", custo: 1, peso: "0,5 kg" },
  // vara: { nome: "Vara (3 m)", custo: 20, peso: "4 kg" },
  // vela: { nome: "Vela", custo: 1, peso: "-" },
  // vidro_tinta: { nome: "Vidro para tinta ou poção", custo: 100, peso: "0,05 kg" }
};