export { default as Swords } from './icons/Swords'
export { default as Skull } from './icons/Skull'
export { default as Add } from './icons/Add'
export { default as Group } from './icons/Group'
export { default as Master } from './icons/Master'
export { default as Graph } from './icons/Graph'
export { default as ChessKnight } from './icons/ChessKnight'
export { default as Git } from './icons/Git'

export type IconName = 'swords' | 'skull' | 'add' | 'group' | 'master' | 'graph' | 'chess-knight' | 'git'